### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by wadie** [phonegap/app#5]
Hi,

I have a Samsung Galaxy J7 and as it appears to be on Google Play Store, is that the phonegap app can't be installed on my device. simply not compatible.

Any input on this ?

**Comment by shazron** [comment]
Issue moved to [phonegap/phonegap-app-developer #441](https://github.com/phonegap/phonegap-app-developer/issues/441) via [**ZenHub**](https://www.zenhub.com/)

**Comment by shazron** [comment]
Moved to https://github.com/phonegap/phonegap-app-developer/issues/441
